version: '3'
services:
  nginx:
    image: nginx:stable-alpine3.17-perl
    container_name: nginx
    restart: always
    volumes:
      - ./html:/usr/share/nginx/html
    ports:
      - "9001:80"
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
