
services:
  mysql:
    image: mysql:8.0.36
    container_name: mysql_server
    environment:
      MYSQL_ROOT_PASSWORD: admin123456 # 使用环境变量提升安全性
      MYSQL_DATABASE: demo # 数据库名称保留
      MYSQL_USER: admin # 非root用户
      MYSQL_PASSWORD: admin123456
    ports:
      - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - default_network

  redis:
    image: redis:6.2.6
    container_name: redis_server
    command: redis-server --appendonly yes # 开启持久化
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - default_network

volumes:
  mysql:
  redis:

networks:
  default_network:
    driver: bridge
