services:
  prometheus:
    image: prom/prometheus:v2.53.0
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitor-net
    restart: unless-stopped # 除非手动停止，否则总是重启
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:10.4.4
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      GF_SECURITY_ADMIN_PASSWORD: secret
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "3000:3000"
    networks:
      - monitor-net
    restart: unless-stopped # 除非手动停止，否则总是重启
    depends_on:
      - prometheus # 确保Grafana在Prometheus服务启动后再启动

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  monitor-net:
    driver: bridge
