services:
  prometheus:
    image: prom/prometheus:v2.53.0
    container_name : prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus # 持久化 Prometheus 数据
    ports:
      - "59090:9090"
    networks:
      - monitor-net
    restart: unless-stopped # 除非手动停止，否则总是重启
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'

  grafana:
    image: grafana/grafana:10.4.4
    container_name : grafana
    volumes:
      - grafana_data:/var/lib/grafana # 持久化 Grafana 数据
      - ./grafana.ini:/etc/grafana/grafana.ini #  Grafana 配置文件
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123456 # 管理员密码
      GF_USERS_ALLOW_SIGN_UP: "false" # 禁止用户自行注册
    ports:
      - "53000:3000"
    networks:
      - monitor-net
    restart: unless-stopped # 除非手动停止，否则总是重启
    depends_on:
      - prometheus # 确保 Grafana 在 Prometheus 服务启动后再启动

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitor-net
    restart: unless-stopped

volumes:
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  monitor-net:
    driver: bridge
