version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab.example.com'
    ports:
      - '80:80'
      # - '443:443'
      - '2222:22'
    volumes:
      - './gitlab.rb:/etc/gitlab/gitlab.rb'
      - 'gitlab-config:/etc/gitlab'
      - 'gitlab-logs:/var/log/gitlab'
      - 'gitlab-data:/var/opt/gitlab'
    networks:
      - gitlab

volumes:
  gitlab-config:
  gitlab-logs:
  gitlab-data:

networks:
  gitlab:
    driver: bridge
