services:
  consul:
    image: consul:1.15.4
    container_name: consul
    volumes:
      - ./consul/data:/consul/data
      - ./consul/config:/consul/config
    ports:
      - "8500:8500"
      - "8600:8600/udp"
    command:
      [
        "agent",
        "-server",
        "-ui",
        "-bootstrap-expect=1",
        "-client=0.0.0.0",
        "-config-dir=/consul/config"
      ]
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8500/v1/status/leader"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - consul-net

networks:
  consul-net:
    driver: bridge
