version: '3.8'

services:
  log:
    image: goharbor/harbor-log:v2.3.0
    container_name: harbor-log
    restart: always
    volumes:
      - ./common/config/log/:/var/log/harbor/
    networks:
      - harbor

  database:
    image: goharbor/harbor-db:v2.3.0
    container_name: harbor-db
    restart: always
    volumes:
      - ./common/config/db/:/var/lib/postgresql/data
    networks:
      - harbor

  registry:
    image: goharbor/registry-photon:v2.3.0
    container_name: registry
    restart: always
    volumes:
      - ./common/config/registry/:/etc/registry/
      - /data/registry:/storage
    networks:
      - harbor

  registryctl:
    image: goharbor/harbor-registryctl:v2.3.0
    container_name: registryctl
    restart: always
    volumes:
      - ./common/config/registryctl/:/etc/registryctl/
      - /data/registry:/storage
    networks:
      - harbor

  core:
    image: goharbor/harbor-core:v2.3.0
    container_name: harbor-core
    restart: always
    volumes:
      - ./common/config/core/:/etc/core/
    networks:
      - harbor

  portal:
    image: goharbor/harbor-portal:v2.3.0
    container_name: harbor-portal
    restart: always
    networks:
      - harbor

  jobservice:
    image: goharbor/harbor-jobservice:v2.3.0
    container_name: harbor-jobservice
    restart: always
    volumes:
      - ./common/config/jobservice:/etc/jobservice/
      - /var/log/jobservice:/var/log/jobservice
    networks:
      - harbor

  redis:
    image: redis:5.0
    container_name: redis
    restart: always
    networks:
      - harbor

  proxy:
    image: goharbor/nginx-photon:v2.3.0
    container_name: nginx
    restart: always
    volumes:
      - ./common/config/nginx/:/etc/nginx/
    networks:
      - harbor
    ports:
      - 80:8080
      - 443:8443

networks:
  harbor:
