version: '3.8'
services:
  vault:
    image: vault:1.10.0 # 使用固定版本而非latest，确保生产环境稳定性
    container_name: vault
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://0.0.0.0:8200"
      VAULT_API_ADDR: "http://0.0.0.0:8200"
      VAULT_CLUSTER_ADDR: "https://vault:8201"
      VAULT_CONFIG_DIR: "/vault/config"
      VAULT_LOCAL_CONFIG: |
        {
          "listener": [{"tcp": {"address": "0.0.0.0:8200", "tls_disable": 1}}],
          "storage": {"file": {"path": "/vault/file"}},
          "ui": true
        }
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config:/vault/config
      - ./vault/file:/vault/file
      - ./vault/logs:/vault/logs
    restart: always
    entrypoint: [ "vault", "server" ]
    command: ""

  # Optional: Vault UI
  vault-ui:
    image: djenriquez/vault-ui
    container_name: vault-ui
    ports:
      - "8000:8000"
    environment:
      VAULT_URL_DEFAULT: "http://vault:8200"
      VAULT_AUTH_DEFAULT: "TOKEN"
      VAULT_TOKEN_DEFAULT: "admin123456"
    depends_on:
      - vault
