version: "3.8"
services:
  apisix:
    image: apache/apisix:3.8.0-debian
    container_name: apisix
    restart: always
    volumes:
      - ./apisix_conf/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    ports:
      - "80:80"
      - "443:443"
      - "9092:9092"
    networks:
      - apisix_network
      
  etcd:
    image: bitnami/etcd:3.4.15
    container_name: etcd-apisix
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    networks:
      - apisix_network

  dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: dashboard-apisix
    restart: always
    volumes:
      - ./dashboard_conf/config.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    ports:
      - "9000:9000"
    networks:
      - apisix_network
networks:
  apisix_network:
    driver: bridge
volumes:
  etcd_data:
    driver: local
