version: '3.8'
services:
  portainer:
    image: outlovecn/portainer-cn:latest
    container_name: portainer
    ports:
      - "40000:9000" # 主界面
      - "40001:8000" # Portainer Agent 端口
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - TZ=Asia/Shanghai # 设置时区
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true # 禁止提升权限
    healthcheck:
      test: [ "CMD-SHELL", "netstat -tuln | grep 9000" ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - portainer

volumes:
  portainer_data:
    driver: local
    
networks:
  portainer:
    driver: bridge
