services:
  goproxy:
    image: goproxy/goproxy:latest
    command: "-listen=0.0.0.0:8081 -cacheDir=/ext"
    ports:
      - "8081:8081"
    restart: always
    environment:
      - HTTP_PROXY=http://host.docker.internal:7890
      - HTTPS_PROXY=http://host.docker.internal:7890
    volumes:
      - ./cacheDir:/ext
